name: Run Minecraft Bot every 25 mins

on:
  schedule:
    - cron: "*/25 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    concurrency:
      group: bot-run
      cancel-in-progress: true

    env:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      BOT_USERNAME: ${{ secrets.BOT_USERNAME }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run bot script
        run: npx ts-node bot.ts
