name: Run Minecraft Bot every 25 minutes

on:
  schedule:
    - cron: "*/25 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Set environment variables from GitHub secrets
        run: |
          echo "SERVER_HOST=${{ secrets.SERVER_HOST }}" >> $GITHUB_ENV
          echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> $GITHUB_ENV
          echo "BOT_USERNAME=${{ secrets.BOT_USERNAME }}" >> $GITHUB_ENV

      - name: Run Minecraft bot
        run: npm run start
